#!/bin/bash

if [[ -f $1 ]]; then
   var=`md5sum $1`
   var=${var%% *}
   name=${1##*/}
   echo "$name=$var"
else 
echo "用法:		        ./gn_make_md5 <file_path>"
echo "file_path:		需要生成md5文件的路径"
echo "输出:		        文件名=md5值"
echo "例如:		        update_T0920.zip=18232312c6848e697e3a7c5172cd3743"
    exit 1
fi

