ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
#gionee add by chenqiang for ois af 20140506
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
#gionee add by chenqiang for ois af 20140506
obj-$(CONFIG_IMX135) += OisCmd.o OisIni.o
