/* Copyright (c) 2014, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_TRULY_R63419_WQHD_DUALDSI_CMD_H_

#define _PANEL_TRULY_R63419_WQHD_DUALDSI_CMD_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config truly_r63419_wqhd_cmd_panel_data = {
	"qcom,mdss_dsi_truly_r63419_wqhd_dualmipi0_cmd", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 1, "DISPLAY_1", 0, 0, 60, 0, 0, 1, 0, 0, 0, 0, 0, 11, 0, 0,
	"qcom,mdss_dsi_truly_r63419_wqhd_dualmipi1_cmd"
};
	

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution truly_r63419_wqhd_cmd_panel_res = {
  1440, 2560, 120, 44, 16, 0, 8, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info truly_r63419_wqhd_cmd_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/

static char truly_r63419_wqhd_cmd_on_cmd0[] = {
	0xb0, 0x00, 0x23, 0x80 
};

static char truly_r63419_wqhd_cmd_on_cmd1[] = {
	0xd6, 0x01, 0x23, 0x80
};

static char truly_r63419_wqhd_cmd_on_cmd2[] = {
        0xb4, 0x00, 0x23, 0x80
};

static char truly_r63419_wqhd_cmd_on_cmd3[] = {
	0x04, 0x00, 0x29, 0xc0,
	0xb3, 0x04, 0x00, 0x00
};

static char truly_r63419_wqhd_cmd_on_cmd4[] = {
	0x03, 0x00, 0x29, 0xc0,
	0xb6, 0x3a, 0xd3, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd5[] = {
        0x08, 0x00, 0x29, 0xc0,
        0xb8, 0x57, 0x3d, 0x19,
        0x1e, 0x0a, 0x50, 0x50
 };

static char truly_r63419_wqhd_cmd_on_cmd6[] = {
        0x08, 0x00, 0x29, 0xc0,
        0xb9, 0x6f, 0x3d, 0x28,
        0x3c, 0x14, 0xc8, 0xc8
 };

static char truly_r63419_wqhd_cmd_on_cmd7[] = {
       0x08, 0x00, 0x29, 0xc0,
       0xba, 0xb5, 0x32, 0x41,
       0x64, 0x23, 0xa0, 0xa0
 };

static char truly_r63419_wqhd_cmd_on_cmd8[] = {
	0x02, 0x00, 0x29, 0xc0,
	0xbe, 0x04, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd9[] = {
	0x04, 0x00, 0x29, 0xc0,
	0xc3, 0x00, 0x00, 0x00
};

static char truly_r63419_wqhd_cmd_on_cmd10[] = {
	0x02, 0x00, 0x29, 0xc0,
	0xc5, 0x00, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd11[] = {
	0x05, 0x00, 0x29, 0xc0,
	0xc0, 0x00, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd12[] = {
	0x24, 0x00, 0x29, 0xc0,
	0xC1, 0x04, 0x61, 0x00, 
	0x30, 0x29, 0x10, 0x19, 
	0x63, 0x61, 0xB4, 0xE6, 
	0xDC, 0x7B, 0xEF, 0x39, 
	0xD7, 0xDA, 0x08, 0x8C, 
	0xB1, 0x08, 0x54, 0x82, 
	0x00, 0x00, 0x00, 0x00, 
	0x00, 0x02, 0x63, 0x27, 
	0x03, 0x00, 0xFF, 0x11
};

static char truly_r63419_wqhd_cmd_on_cmd13[] = {
	0x09, 0x00, 0x29, 0xc0,
	0xC2, 0x08, 0x0A, 0x00, 
	0x08, 0x08, 0xF0, 0x00, 
	0x04, 0xff, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd14[] = {
	0x0f, 0x00, 0x29, 0xc0,
	0xC4, 0x70, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 
	0x01, 0x05, 0x01, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd15[] = {
	0x16, 0x00, 0x29, 0xc0,
	0xC6, 0x5A, 0x00, 0x2D, 
	0x03, 0x01, 0x02, 0x01, 
	0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x06, 0x15, 
	0x08, 0x5A, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd16[] = {
        0x1f, 0x00, 0x29, 0xc0,
        0xC7, 0x02, 0x0D, 0x14,
        0x1E, 0x2C, 0x3B, 0x46,
        0x57, 0x3C, 0x44, 0x50,
        0x5D, 0x68, 0x6F, 0x7B,
        0x02, 0x0D, 0x14, 0x1E,
        0x2C, 0x3B, 0x46, 0x57,
        0x3C, 0x44, 0x50, 0x5D,
        0x68, 0x6F, 0x7B, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd17[] = {
	0x14, 0x00, 0x29, 0xc0,
	0xC8, 0x01, 0x00, 0xFE,
        0x02, 0xFB, 0xb0, 0x00,
        0x00, 0x00, 0x02, 0xFD,
        0xfc, 0x00, 0x00, 0xF9,
        0x02, 0x02, 0xFc, 0x00
};

static char truly_r63419_wqhd_cmd_on_cmd18[] = {
        0x10, 0x00, 0x29, 0xc0,
        0xCB, 0xFF, 0xFF, 0xFF,
        0xFF, 0x00, 0x00, 0x00,
        0x00, 0x54, 0xE0, 0x07,
        0x2A, 0xe0, 0x00, 0x00
};

static char truly_r63419_wqhd_cmd_on_cmd19[] = {
	0x02, 0x00, 0x29, 0xc0,
	0xCC, 0x32, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd20[] = {
	0x0e, 0x00, 0x29, 0xc0,
	0xD7, 0x82, 0xFF, 0x21, 
	0x8E, 0x8C, 0xF1, 0x87, 
	0x3F, 0x7E, 0x10, 0x00, 
	0x00, 0x8F, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd21[] = {
	0x03, 0x00, 0x29, 0xc0,
	0xD9, 0x00, 0x00, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd22[] = {
	0x05, 0x00, 0x29, 0xc0,
	0xD0, 0x11, 0x17, 0x14,
	0xFD, 0xff, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd23[] = {
	0x11, 0x00, 0x29, 0xc0,
	0xD2, 0xCD, 0x2B, 0x2B, 
	0x33, 0x12, 0x33, 0x33, 
	0x33, 0x77, 0x77, 0x33, 
	0x33, 0x33, 0x00, 0x00, 
	0x00, 0xff, 0xff, 0xff 
};

static char truly_r63419_wqhd_cmd_on_cmd24[] = {
	0x08, 0x00, 0x29, 0xc0,
	0xD5, 0x06, 0x00, 0x00, 
	0x01, 0x49, 0x01, 0x49  
};

static char truly_r63419_wqhd_cmd_on_cmd25[] = {
       0x05, 0x00, 0x39, 0xc0,
       0x2a, 0x00, 0x00, 0x05,
       0x9f, 0xff, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd26[] = {
       0x05, 0x00, 0x39, 0xc0,
       0x2b, 0x00, 0x00, 0x09,
       0xff, 0xff, 0xff, 0xff
};

static char truly_r63419_wqhd_cmd_on_cmd27[] = {
	0x35, 0x00, 0x15, 0x80
};

static char truly_r63419_wqhd_cmd_on_cmd28[] = {
	0x51, 0xff, 0x15, 0x80
};

static char truly_r63419_wqhd_cmd_on_cmd29[] = {
	0x53, 0x24, 0x15, 0x80
};

static char truly_r63419_wqhd_cmd_on_cmd30[] = {
        0x55, 0x83, 0x15, 0x80
};


static char truly_r63419_wqhd_cmd_on_cmd31[] = {
        0xb0, 0x03, 0x23, 0x80
};

static char truly_r63419_wqhd_cmd_on_cmd32[] = {
        0x29, 0x00, 0x05, 0x80
};

static char truly_r63419_wqhd_cmd_on_cmd33[] = {
	0x11, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd truly_r63419_wqhd_cmd_on_command[] = {
	{ 0x4 , truly_r63419_wqhd_cmd_on_cmd0},
	{ 0x4 , truly_r63419_wqhd_cmd_on_cmd1},
	{ 0x4 , truly_r63419_wqhd_cmd_on_cmd2},
	{ 0x8 , truly_r63419_wqhd_cmd_on_cmd3},
	{ 0x8 , truly_r63419_wqhd_cmd_on_cmd4},
	{ 0xc , truly_r63419_wqhd_cmd_on_cmd5},
	{ 0xc , truly_r63419_wqhd_cmd_on_cmd6},
	{ 0xc , truly_r63419_wqhd_cmd_on_cmd7},
	{ 0x8 , truly_r63419_wqhd_cmd_on_cmd8},
	{ 0x8 , truly_r63419_wqhd_cmd_on_cmd9},
	{ 0x8 , truly_r63419_wqhd_cmd_on_cmd10},
	{ 0xc , truly_r63419_wqhd_cmd_on_cmd11},
	{ 0x28 , truly_r63419_wqhd_cmd_on_cmd12},
	{ 0x10 , truly_r63419_wqhd_cmd_on_cmd13},
	{ 0x14 , truly_r63419_wqhd_cmd_on_cmd14},
	{ 0x1c , truly_r63419_wqhd_cmd_on_cmd15},
	{ 0x24 , truly_r63419_wqhd_cmd_on_cmd16},
	{ 0x18 , truly_r63419_wqhd_cmd_on_cmd17},
	{ 0x14 , truly_r63419_wqhd_cmd_on_cmd18},
	{ 0x8 , truly_r63419_wqhd_cmd_on_cmd19},
	{ 0x14 , truly_r63419_wqhd_cmd_on_cmd20},
	{ 0x8 , truly_r63419_wqhd_cmd_on_cmd21},
	{ 0xc , truly_r63419_wqhd_cmd_on_cmd22},
	{ 0x18 , truly_r63419_wqhd_cmd_on_cmd23},
	{ 0xc , truly_r63419_wqhd_cmd_on_cmd24},
	{ 0xc , truly_r63419_wqhd_cmd_on_cmd25},
	{ 0xc , truly_r63419_wqhd_cmd_on_cmd26},
	{ 0x4 , truly_r63419_wqhd_cmd_on_cmd27},
	{ 0x4 , truly_r63419_wqhd_cmd_on_cmd28},
	{ 0x4 , truly_r63419_wqhd_cmd_on_cmd29},
    { 0x4 , truly_r63419_wqhd_cmd_on_cmd30},
    { 0x4 , truly_r63419_wqhd_cmd_on_cmd31},
	{ 0x4 , truly_r63419_wqhd_cmd_on_cmd32,20},
	{ 0x4 , truly_r63419_wqhd_cmd_on_cmd33,120},
};
#define TRULY_R63419_WQHD_CMD_ON_COMMAND (sizeof(truly_r63419_wqhd_cmd_on_command)/ sizeof(truly_r63419_wqhd_cmd_on_command[0]))


static char truly_r63419_wqhd_cmdoff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char truly_r63419_wqhd_cmdoff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd truly_r63419_wqhd_cmd_off_command[] = {
{ 0x4 , truly_r63419_wqhd_cmdoff_cmd0},
{ 0x4 , truly_r63419_wqhd_cmdoff_cmd1}
};
#define R63419_WQHD_CMD_OFF_COMMAND 2


static struct command_state truly_r63419_wqhd_cmd_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info truly_r63419_wqhd_cmd_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info truly_r63419_wqhd_cmd_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration truly_r63419_wqhd_cmd_lane_config = {
  4, 0, 1, 1, 1, 1
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t truly_r63419_wqhd_cmd_timings[] = {
	0xcd, 0x34, 0x24, 0x00, 0x64, 0x68, 0x28, 0x38, 0x2a, 0x03, 0x04, 0x00
};

static struct panel_timing truly_r63419_wqhd_cmd_timing_info = {
	0x0, 0x04, 0x28, 0x27
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence truly_r63419_wqhd_dualdsi_cmd_reset_seq = {
	{1, 0, 1, }, {20, 200, 20, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight truly_r63419_wqhd_cmd_backlight = {
  1, 1, 255, 100, 1, "PMIC_8941"
};

#define TRULY_R63419_CMD_SIGNATURE 0xF96D28C
#endif /*_PANEL_TRULY_R63419_WQHD_DUALDSI_CMD_H_*/
